skip_branch_with_pr: true

image:
  - Visual Studio 2019
  - ubuntu

cache:
  - c:\tools\vcpkg\installed\

install:
  - pwsh: |
      if ($isLinux) {
        ./linux/install.ps1
      } else {
        ./windows/install.ps1
      }

build_script:
  - pwsh: |
      if ($isLinux) {
        ./linux/build.ps1
      } else {
        ./windows/build.ps1 -VcpkgToolchain c:\tools\vcpkg\scripts\buildsystems\vcpkg.cmake
      }

after_build:
  - pwsh: |
      if ($isLinux) {
        ./linux/pack.ps1
      } else {
        ./windows/pack.ps1
      }

artifacts:
  - path: tdlib.windows.zip
    name: tdlib.windows
  - path: tdlib.linux.zip
    name: tdlib.linux

deploy:
  provider: GitHub
  auth_token:
    secure: R1U294hAtzPMqiWT3Ioon2d4ZmnD86eRCI7AyzKVcAcz7+jv/vZsePY6sj2HXz53
  artifact: tdlib.windows,tdlib.linux
  on:
    APPVEYOR_REPO_TAG: true
